### ISSUE TITLE
withdrawn

### ISSUE THREAD

**Issue by tkphd** [usnistgov/CRPI#4]
withdrawn

**Comment by mlzimmer** [comment]
Hi Trevor, I'm currently fixing these in a separate fork that I'll merge soon. 

For some reason I cannot find these public repository guidelines on the odiwiki, it only shoes a work in progress page for the GitHubReposManagementGuide section. I'd like to make sure that while I am fixing these I cover all of it, is there a place I can look for the rules while they are being edited? 

Additionally is there a repo on the usnistgov group that you could point to that is a good example of a satisfactory compliant Readme?

**Comment by tkphd** [comment]
Check http://github.nist.gov and its links. Thanks!

**Comment by mlzimmer** [comment]
Okay, I've done my best to add the suggested edits for compliance.
See #5 and readme as well as updated license
